
import oracledb
from config import Config
from db import get_oracle_connection_billing
from case.connote_update import p_get_job_cnote_audit
def p_get_job_cnote_audit(p_cnote):
    try:
        # Establish connection to the database (adjust credentials as needed)
        connection = get_oracle_connection_billing()  # Assuming a connection function is available
        if connection:
            cursor = connection.cursor()

            # Define the SQL query for job_cnote_audit
            query = f"""
               SELECT
         TRUNC (CNOTE_DATE) TRUNC_CNOTE_DATE,
          CNOTE_BRANCH_ID BRANCH,
          TRUNC (CNOTE_DATE) AWB_DATE,
          BRANCH_DESC BRANCH_NAME,
          A.CNOTE_NO AWB,
          CNOTE_CUST_NO CUSTOMER_ID,
          CUST_NAME CUSTOMER_NAME,
          CNOTE_SERVICES_CODE SERVICE_CODE,
          CNOTE_ORIGIN ORIGIN_ID,
          ORIGIN.CITY_NAME ORIGIN_NAME,             --o.city_name origin_name,
          CNOTE_DESTINATION DESTINATION_ID,
          DESTINATION.CITY_NAME DESTINATION_NAME, --d.city_name destination_name,
          CNOTE_QTY PCS,
          CNOTE_WEIGHT WEIGHT_KG,
          DECODE (CNOTE_PAYMENT_TYPE, '1', CNOTE_AMOUNT, 0) CASH,
          DECODE (CNOTE_PAYMENT_TYPE, '2', CNOTE_AMOUNT, 0) CREDIT,
          NVL (CNOTE_AMOUNT, 0) AMOUNT,
          NVL (CNOTE_GOODS_VALUE, 0) GOODS_VALUE,
          case 
            when CNOTE_PAYMENT_TYPE='1' then 'CASH'
            when CNOTE_PAYMENT_TYPE='2' then 'CREDIT'
            when CNOTE_PAYMENT_TYPE='3' then 'COD'
            when CNOTE_PAYMENT_TYPE='4' then 'E-PAYMET'
            when CNOTE_PAYMENT_TYPE='6' then 'CONGKIR'
          END CNOTE_PAYMENT_TYPE,
          NVL (CNOTE_INSURANCE_VALUE, 0) INSURANCE_VALUE, --, NVL( (SELECT /*+ PARALLEL (A,16) */ 'Y'  FROM ACR_DINV_TR PARTITION(ACR_DINV_TR_01_14) A WHERE DINV_CNOTE_NO = CNOTE_NO),(SELECT /*+ PARALLEL (A,16) */  'Y' FROM ACR_DINV_REV PARTITION(ACR_DINV_REV_01_14) A WHERE DINV_CNOTE_NO = CNOTE_NO)) CNOTE_INVOICED
          CNOTE_CURRENCY,
          CNOTE_CURC_RATE,
          CNOTE_PRINTED,
          CNOTE_MANIFESTED,
          CNOTE_INVOICED,
          CNOTE_CANCEL,
          CNOTE_QUICK,
          0 BILNOTE_AMOUNT,
          CUST_TYPE,
          CUST_PARENT_ID,
          '' REGINV,
          '' REGINV_DATE,
          '' DOC_NO,
            F_GET_RUNSHEET(AWB) RSHEET_NO,
            F_GET_RUNSHEET_DATE(AWB) POD_DATE,
            REPJNE.F_GET_RUNSHEET_POD_STATUS(AWB) POD_STATUS,
            REPJNE.F_GET_RUNSHEET_POD_FLAG(AWB) POD_FLAG,
            REPJNE.F_GET_RUNSHEET_RECEIVER(AWB) POD_RECEIVER,
          CNOTE_RECEIVER_NAME,
          CNOTE_HOLD_REASON,
          CUST_DISC_IC INV_CUST_DIC, 
          CUST_DISC_DM INV_CUST_DDM, 
          CUST_DISC_IN INV_CUST_DIN, 
          ''MFCNOTE_INB_NO, 
          ''BILNOTE_NO,
          CNOTE_VUSER,
          CNOTE_VDATE,
          CNOTE_POD_RECEIVER,
          CNOTE_REFNO,
          CNOTE_NOTICE,
          CNOTE_SPECIAL_INS,
          CNOTE_GOODS_DESCR CNOTE_GOODS_DESCR_INS,
          '' CASHLESS_HOVER_DOC,
          '' CASHLESS_HOVER_DATE,
          '' CASHLESS_SELLER_ID,
          '' CASHLESS_CUST_ID,
          F_GET_MANIFEST_STATUS(CNOTE_NO,'3') MFCNOTE_INB_DATE,
          F_GET_MANIFEST_STATUS(CNOTE_NO,'1') MFCNOTE_OUTB_NO,
          null MFCNOTE_OUTB_DATE,
          F_GET_MANIFEST_STATUS(CNOTE_NO,'2') MFCNOTE_TRANSIT_NO,
          null MFCNOTE_TRANSIT_DATE,
          '' HOMI_NO,
          '' HOMI_DATE,
          '' TEXT1,
          '' TEXT2,
          '' TDATE,
          R_CNOTE_FREIGHT_CHARGE, R_CNOTE_SURCHARGE,R_CNOTE_PACKING_FEE,R_CNOTE_DISCOUNT, CNOTE_CARD_DISC, CNOTE_OTHER_FEE, CNOTE_ADDITIONAL_FEE,
          (SELECT 'Y' FROM T_CNOTE_AUD_2020 WHERE AWB=CNOTE_NO) T_2020,
          (SELECT 'Y' FROM T_CNOTE_AUD_2021 WHERE AWB=CNOTE_NO) T_2021,
          CNOTE_GOODS_TYPE
          , NULL RUNSHEET_DATE --,F_GET_POD_STATUS(AWB,2) RUNSHEET_DATE
          , NULL COURIER_ID --,F_GET_POD_STATUS(AWB,4) COURIER_ID
          , NULL COURIER_NAME --,F_GET_POD_STATUS(AWB,5) COURIER_NAME 
     FROM CMS_CNOTE A,
          ORA_BRANCH B,
          CMS_CUST C,
          CMS_CITY ORIGIN,
          CMS_CITY DESTINATION,
          (SELECT CNOTE_NO AWB,  NVL(CNOTE_CANCEL,'N') AWB_CENCEL FROM REPJNE.CMS_CNOTE) F,
          R_CMS_CNOTE G
    WHERE  ORIGIN.CITY_CODE(+) = CNOTE_ORIGIN
          AND DESTINATION.CITY_CODE(+) = CNOTE_DESTINATION
          AND BRANCH_CODE(+) = CNOTE_BRANCH_ID
          AND CNOTE_CUST_NO = CUST_ID(+)                               
          AND CNOTE_BRANCH_ID = CUST_BRANCH(+)
          AND NVL(CNOTE_CANCEL,'N') ='N'
          AND F.AWB(+)=CNOTE_NO
          AND CNOTE_SERVICES_CODE NOT IN ('CML')
          AND CNOTE_NO=:cnote_no      
--          AND NOT EXISTS (SELECT 1 FROM T_CNOTE_AUD_2020 WHERE AWB=CNOTE_NO)
--          AND NOT EXISTS (SELECT 1 FROM T_CNOTE_AUD_2021 WHERE AWB=CNOTE_NO)
          AND CNOTE_NO=R_CNOTE_NO(+)
            """

            # Execute the query with the provided CNOTE_NO
            cursor.execute(query, {"cnote_no": p_cnote})

            # Fetch the result
            result = cursor.fetchall()

            for row in result:
                trunc_cnote_date = row[0]
                t_2020 = row[-3]
                t_2021 = row[-2]

                # Check the year and T_2020 flag
                if trunc_cnote_date.year == 2020:
                    if t_2020 is None:  # NULL means it has not been inserted yet
                        # Insert into T_CNOTE_AUD_2020
                        insert_query = \
                                               """
                                       INSERT INTO T_CNOTE_AUD_2020 (
                                       TRUNC_CNOTE_DATE, \
                                                                    BRANCH, \
                                                                     AWB_DATE, \
                                                                     BRANCH_NAME, \
                                                                     AWB, \
                                                                     CUSTOMER_ID, \
                                                                     CUSTOMER_NAME, \
                                                                     SERVICE_CODE, \
                                                                     ORIGIN_ID, \
                                                                     ORIGIN_NAME, \
                                                                     DESTINATION_ID, \
                                                                     DESTINATION_NAME, \
                                                                     PCS, \
                                                                     WEIGHT_KG, \
                                                                     CASH, \
                                                                     CREDIT, \
                                                                     AMOUNT, \
                                                                     GOODS_VALUE, \
                                                                     CNOTE_PAYMENT_TYPE, \
                                                                     INSURANCE_VALUE, \
                                                                     CNOTE_CURRENCY, \
                                                                     CNOTE_CURC_RATE, \
                                                                     CNOTE_PRINTED,
                                           CNOTE_MANIFESTED,
                                           CNOTE_INVOICED,
                                           CNOTE_CANCEL,
                                           CNOTE_QUICK,
                                           BILNOTE_AMOUNT,
                                           CUST_TYPE,
                                           CUST_PARENT_ID,
                                           REGINV,
                                           REGINV_DATE,
                                           DOC_NO,
                                           CNOTE_RECEIVER_NAME,
                                           CNOTE_OTHER_FEE,
                                           CNOTE_HOLD_REASON,
                                           INV_CUST_DIC,
                                           INV_CUST_DDM,
                                           INV_CUST_DIN,
                                           MFCNOTE_INB_NO,
                                           BILNOTE_NO,
                                           CNOTE_VUSER,
                                           CNOTE_VDATE,
                                           CNOTE_REFNO,
                                           CNOTE_NOTICE,
                                           CNOTE_SPECIAL_INS,
                                           CNOTE_GOODS_DESCR_INS,
                                           CASHLESS_HOVER_DOC,
                                           CASHLESS_HOVER_DATE,
                                           CASHLESS_SELLER_ID,
                                           CASHLESS_CUST_ID,
                                           MFCNOTE_INB_DATE,
                                           MFCNOTE_OUTB_NO,
                                           MFCNOTE_OUTB_DATE,
                                           MFCNOTE_TRANSIT_NO,
                                           MFCNOTE_TRANSIT_DATE,
                                           HOMI_NO,
                                           HOMI_DATE,
                                           TEXT1,
                                           TEXT2,
                                           TDATE,
                                           FREIGHT_CHARGE,
                                           SURCHARGE,
                                           PACKING_FEE,
                                           SPECIAL_AMOUNT,
                                           DISCOUNT,
                                           DISCOUNT_CARD,
                                           OTHER_FEE,
                                           ADDITIONAL_FEE,
                                           RUNSHEET,
                                           POD_DATE,
                                           POD_STATUS,
                                           POD_FLAG,
                                           CNOTE_POD_RECEIVER
                                       )
                                       VALUES (
                                                  :trunc_cnote_date,
                                                  :branch,
                                                  :awb_date,
                                                  :branch_name,
                                                  :awb,
                                                  :customer_id,
                                                  :customer_name,
                                                  :service_code,
                                                  :origin_id,
                                                  :origin_name,
                                                  :destination_id,
                                                  :destination_name,
                                                  :pcs,
                                                  :weight_kg,
                                                  :cash,
                                                  :credit,
                                                  :amount,
                                                  :goods_value,
                                                  :cnote_payment_type,
                                                  :insurance_value,
                                                  :cnote_currency,
                                                  :cnote_curc_rate,
                                                  :cnote_printed,
                                                  :cnote_manifested,
                                                  :cnote_invoiced,
                                                  :cnote_cancel,
                                                  :cnote_quick,
                                                  :bilnote_amount,
                                                  :cust_type,
                                                  :cust_parent_id,
                                                  :reginv,
                                                  :reginv_date,
                                                  :doc_no,
                                                  :cnote_receiver_name,
                                                  :cnote_other_fee,
                                                  :cnote_hold_reason,
                                                  :inv_cust_dic,
                                                  :inv_cust_ddm,
                                                  :inv_cust_din,
                                                  :mfcnote_inb_no,
                                                  :bilnote_no,
                                                  :cnote_vuser,
                                                  :cnote_vdate,
                                                  :cnote_refno,
                                                  :cnote_notice,
                                                  :cnote_special_ins,
                                                  :cnote_goods_descr_ins,
                                                  :cashless_hover_doc,
                                                  :cashless_hover_date,
                                                  :cashless_seller_id,
                                                  :cashless_cust_id,
                                                  REPJNE.GET_DATA_SPLIT('~', :mfcnote_inb_date, 2),
                                                  REPJNE.GET_DATA_SPLIT('~', :mfcnote_outb_no, 1),
                                                  REPJNE.GET_DATA_SPLIT('~', :mfcnote_outb_date, 2),
                                                  REPJNE.GET_DATA_SPLIT('~', :mfcnote_transit_no, 1),
                                                  REPJNE.GET_DATA_SPLIT('~', :mfcnote_transit_date, 2),
                                                  :homi_no,
                                                  :homi_date,
                                                  :text1,
                                                  :text2,
                                                  :tdate,
                                                  :freight_charge,
                                                  :surcharge,
                                                  :packing_fee,
                                                  0,  -- SPECIAL_AMOUNT is set to 0
                                                  :discount,
                                                  :discount_card,
                                                  :other_fee,
                                                  :additional_fee,
                                                  :runsheet,
                                                  :pod_date,
                                                  :pod_status,
                                                  :pod_flag,
                                                  :pod_receiver
                                              ) \
                                       """

                        # Eksekusi query insert
                        cursor.execute(insert_query, {
                            "trunc_cnote_date": trunc_cnote_date,
                            "branch": row[1],
                            "awb_date": row[2],
                            "branch_name": row[3],
                            "awb": row[4],
                            "customer_id": row[5],
                            "customer_name": row[6],
                            "service_code": row[7],
                            "origin_id": row[8],
                            "origin_name": row[9],
                            "destination_id": row[10],
                            "destination_name": row[11],
                            "pcs": row[12],
                            "weight_kg": row[13],
                            "cash": row[14],
                            "credit": row[15],
                            "amount": row[16],
                            "goods_value": row[17],
                            "cnote_payment_type": row[18],
                            "insurance_value": row[19],
                            "cnote_currency": row[20],
                            "cnote_curc_rate": row[21],
                            "cnote_printed": row[22],
                            "cnote_manifested": row[23],
                            "cnote_invoiced": row[24],
                            "cnote_cancel": row[25],
                            "cnote_quick": row[26],
                            "bilnote_amount": row[27],
                            "cust_type": row[28],
                            "cust_parent_id": row[29],
                            "reginv": row[30],
                            "reginv_date": row[31],
                            "doc_no": row[32],
                            "cnote_receiver_name": row[33],
                            "cnote_other_fee": row[34],
                            "cnote_hold_reason": row[35],
                            "inv_cust_dic": row[36],
                            "inv_cust_ddm": row[37],
                            "inv_cust_din": row[38],
                            "mfcnote_inb_no": row[39],
                            "bilnote_no": row[40],
                            "cnote_vuser": row[41],
                            "cnote_vdate": row[42],
                            "cnote_refno": row[43],
                            "cnote_notice": row[44],
                            "cnote_special_ins": row[45],
                            "cnote_goods_descr_ins": row[46],
                            "cashless_hover_doc": row[47],
                            "cashless_hover_date": row[48],
                            "cashless_seller_id": row[49],
                            "cashless_cust_id": row[50],
                            "mfcnote_inb_date": row[51],
                            "mfcnote_outb_no": row[52],
                            "mfcnote_outb_date": row[53],
                            "mfcnote_transit_no": row[54],
                            "mfcnote_transit_date": row[55],
                            "homi_no": row[56],
                            "homi_date": row[57],
                            "text1": row[58],
                            "text2": row[59],
                            "tdate": row[60],
                            "freight_charge": row[61],
                            "surcharge": row[62],
                            "packing_fee": row[63],
                            "discount": row[64],
                            "discount_card": row[65],
                            "other_fee": row[66],
                            "additional_fee": row[67],
                            "runsheet": row[68],
                            "pod_date": row[69],
                            "pod_status": row[70],
                            "pod_flag": row[71],
                            "pod_receiver": row[72]
                        })
                    else:
                        # Update the record in T_CNOTE_AUD_2020
                        update_query = """
                                       UPDATE T_CNOTE_AUD_2020
                                       SET TRUNC_CNOTE_DATE      = :trunc_cnote_date,
                                           BRANCH                = :branch,
                                           AWB_DATE              = :awb_date,
                                           BRANCH_NAME           = :branch_name,
                                           CUSTOMER_ID           = :customer_id,
                                           CUSTOMER_NAME         = :customer_name,
                                           SERVICE_CODE          = :service_code,
                                           ORIGIN_ID             = :origin_id,
                                           ORIGIN_NAME           = :origin_name,
                                           DESTINATION_ID        = :destination_id,
                                           DESTINATION_NAME      = :destination_name,
                                           PCS                   = :pcs,
                                           WEIGHT_KG             = :weight_kg,
                                           CASH                  = :cash,
                                           CREDIT                = :credit,
                                           AMOUNT                = :amount,
                                           GOODS_VALUE           = :goods_value,
                                           CNOTE_PAYMENT_TYPE    = :cnote_payment_type,
                                           INSURANCE_VALUE       = :insurance_value,
                                           CNOTE_CURRENCY        = :cnote_currency,
                                           CNOTE_CURC_RATE       = :cnote_curc_rate,
                                           CNOTE_PRINTED         = :cnote_printed,
                                           CNOTE_MANIFESTED      = :cnote_manifested,
                                           CNOTE_INVOICED        = :cnote_invoiced,
                                           CNOTE_CANCEL          = :cnote_cancel,
                                           CNOTE_QUICK           = :cnote_quick,
                                           BILNOTE_AMOUNT        = :bilnote_amount,
                                           CUST_TYPE             = :cust_type,
                                           CUST_PARENT_ID        = :cust_parent_id,
                                           DOC_NO                = :doc_no,
                                           CNOTE_RECEIVER_NAME   = :cnote_receiver_name,
                                           CNOTE_OTHER_FEE       = :cnote_other_fee,
                                           CNOTE_HOLD_REASON     = :cnote_hold_reason,
                                           INV_CUST_DIC          = :inv_cust_dic,
                                           INV_CUST_DDM          = :inv_cust_ddm,
                                           INV_CUST_DIN          = :inv_cust_din,
                                           CNOTE_VUSER           = :cnote_vuser,
                                           CNOTE_VDATE           = :cnote_vdate,
                                           CNOTE_REFNO           = :cnote_refno,
                                           CNOTE_NOTICE          = :cnote_notice,
                                           CNOTE_SPECIAL_INS     = :cnote_special_ins,
                                           CNOTE_GOODS_DESCR_INS = :cnote_goods_descr_ins,
                                           FREIGHT_CHARGE        = :freight_charge,
                                           SURCHARGE             = :surcharge,
                                           PACKING_FEE           = :packing_fee,
                                           DISCOUNT              = :discount,
                                           DISCOUNT_CARD         = :discount_card,
                                           OTHER_FEE             = :other_fee,
                                           ADDITIONAL_FEE        = :additional_fee,
                                           MFCNOTE_INB_DATE      = REPJNE.GET_DATA_SPLIT('~', :mfcnote_inb_date, 2),
                                           MFCNOTE_OUTB_NO       = REPJNE.GET_DATA_SPLIT('~', :mfcnote_outb_no, 1),
                                           MFCNOTE_OUTB_DATE     = REPJNE.GET_DATA_SPLIT('~', :mfcnote_outb_date, 2),
                                           MFCNOTE_TRANSIT_NO    = REPJNE.GET_DATA_SPLIT('~', :mfcnote_transit_no, 1),
                                           MFCNOTE_TRANSIT_DATE  = REPJNE.GET_DATA_SPLIT('~', :mfcnote_transit_date, 2),
                                           RUNSHEET              = :runsheet,
                                           POD_DATE              = :pod_date,
                                           POD_FLAG              = :pod_flag,
                                           POD_STATUS            = :pod_status,
                                           CNOTE_POD_RECEIVER    = :pod_receiver
                                       WHERE AWB = :awb \
                                       """

                        # Execute the update query
                        cursor.execute(update_query, {
                            "awb": row[4],
                            "trunc_cnote_date": row[0],
                            "branch": row[1],
                            "awb_date": row[2],
                            "branch_name": row[3],
                            "customer_id": row[5],
                            "customer_name": row[6],
                            "service_code": row[7],
                            "origin_id": row[8],
                            "origin_name": row[9],
                            "destination_id": row[10],
                            "destination_name": row[11],
                            "pcs": row[12],
                            "weight_kg": row[13],
                            "cash": row[14],
                            "credit": row[15],
                            "amount": row[16],
                            "goods_value": row[17],
                            "cnote_payment_type": row[18],
                            "insurance_value": row[19],
                            "cnote_currency": row[20],
                            "cnote_curc_rate": row[21],
                            "cnote_printed": row[22],
                            "cnote_manifested": row[23],
                            "cnote_invoiced": row[24],
                            "cnote_cancel": row[25],
                            "cnote_quick": row[26],
                            "bilnote_amount": row[27],
                            "cust_type": row[28],
                            "cust_parent_id": row[29],
                            "doc_no": row[30],
                            "cnote_receiver_name": row[31],
                            "cnote_other_fee": row[32],
                            "cnote_hold_reason": row[33],
                            "inv_cust_dic": row[34],
                            "inv_cust_ddm": row[35],
                            "inv_cust_din": row[36],
                            "cnote_vuser": row[37],
                            "cnote_vdate": row[38],
                            "cnote_refno": row[39],
                            "cnote_notice": row[40],
                            "cnote_special_ins": row[41],
                            "cnote_goods_descr_ins": row[42],
                            "freight_charge": row[43],
                            "surcharge": row[44],
                            "packing_fee": row[45],
                            "discount": row[46],
                            "discount_card": row[47],
                            "other_fee": row[48],
                            "additional_fee": row[49],
                            "mfcnote_inb_date": row[50],
                            "mfcnote_outb_no": row[51],
                            "mfcnote_outb_date": row[52],
                            "mfcnote_transit_no": row[53],
                            "mfcnote_transit_date": row[54],
                            "runsheet": row[55],
                            "pod_date": row[56],
                            "pod_flag": row[57],
                            "pod_status": row[58],
                            "pod_receiver": row[59]
                        })
                    if trunc_cnote_date.year == 2021:  # Memeriksa apakah tahun trunc_cnote_date adalah 2021
                        if t_2021 in [None, 'N']:  # Memeriksa apakah T_2021 adalah NULL atau 'N'
                            # Query untuk insert data
                            insert_query_2021 = """
                                                INSERT INTO T_CNOTE_AUD_2021 (
                                                    TRUNC_CNOTE_DATE,
                                                    BRANCH,
                                                    AWB_DATE,
                                                    BRANCH_NAME,
                                                    AWB,
                                                    CUSTOMER_ID,
                                                    CUSTOMER_NAME,
                                                    SERVICE_CODE,
                                                    ORIGIN_ID,
                                                    ORIGIN_NAME,
                                                    DESTINATION_ID,
                                                    DESTINATION_NAME,
                                                    PCS,
                                                    WEIGHT_KG,
                                                    CASH,
                                                    CREDIT,
                                                    AMOUNT,
                                                    GOODS_VALUE,
                                                    CNOTE_PAYMENT_TYPE,
                                                    INSURANCE_VALUE,
                                                    CNOTE_CURRENCY,
                                                    CNOTE_CURC_RATE,
                                                    CNOTE_PRINTED,
                                                    CNOTE_MANIFESTED,
                                                    CNOTE_INVOICED,
                                                    CNOTE_CANCEL,
                                                    CNOTE_QUICK,
                                                    BILNOTE_AMOUNT,
                                                    CUST_TYPE,
                                                    CUST_PARENT_ID,
                                                    REGINV,
                                                    REGINV_DATE,
                                                    DOC_NO,
                                                    CNOTE_RECEIVER_NAME,
                                                    CNOTE_OTHER_FEE,
                                                    CNOTE_HOLD_REASON,
                                                    INV_CUST_DIC,
                                                    INV_CUST_DDM,
                                                    INV_CUST_DIN,
                                                    MFCNOTE_INB_NO,
                                                    BILNOTE_NO,
                                                    CNOTE_VUSER,
                                                    CNOTE_VDATE,
                                                    CNOTE_REFNO,
                                                    CNOTE_NOTICE,
                                                    CNOTE_SPECIAL_INS,
                                                    CNOTE_GOODS_DESCR_INS,
                                                    CASHLESS_HOVER_DOC,
                                                    CASHLESS_HOVER_DATE,
                                                    CASHLESS_SELLER_ID,
                                                    CASHLESS_CUST_ID,
                                                    MFCNOTE_INB_DATE,
                                                    MFCNOTE_OUTB_NO,
                                                    MFCNOTE_OUTB_DATE,
                                                    MFCNOTE_TRANSIT_NO,
                                                    MFCNOTE_TRANSIT_DATE,
                                                    HOMI_NO,
                                                    HOMI_DATE,
                                                    TEXT1,
                                                    TEXT2,
                                                    TDATE,
                                                    FREIGHT_CHARGE,
                                                    SURCHARGE,
                                                    PACKING_FEE,
                                                    SPECIAL_AMOUNT,
                                                    DISCOUNT,
                                                    DISCOUNT_CARD,
                                                    OTHER_FEE,
                                                    ADDITIONAL_FEE,
                                                    RUNSHEET,
                                                    POD_DATE,
                                                    POD_STATUS,
                                                    POD_FLAG,
                                                    CNOTE_POD_RECEIVER,
                                                    PUBLISH_RATE,
                                                    RUNSHEET_DATE,
                                                    COURIER_ID,
                                                    COURIER_NAME
                                                )
                                                VALUES (
                                                           :trunc_cnote_date,
                                                           :branch,
                                                           :awb_date,
                                                           :branch_name,
                                                           :awb,
                                                           :customer_id,
                                                           :customer_name,
                                                           :service_code,
                                                           :origin_id,
                                                           :origin_name,
                                                           :destination_id,
                                                           :destination_name,
                                                           :pcs,
                                                           :weight_kg,
                                                           :cash,
                                                           :credit,
                                                           :amount,
                                                           :goods_value,
                                                           :cnote_payment_type,
                                                           :insurance_value,
                                                           :cnote_currency,
                                                           :cnote_curc_rate,
                                                           :cnote_printed,
                                                           :cnote_manifested,
                                                           :cnote_invoiced,
                                                           :cnote_cancel,
                                                           :cnote_quick,
                                                           :bilnote_amount,
                                                           :cust_type,
                                                           :cust_parent_id,
                                                           :reginv,
                                                           :reginv_date,
                                                           :doc_no,
                                                           :cnote_receiver_name,
                                                           :cnote_other_fee,
                                                           :cnote_hold_reason,
                                                           :inv_cust_dic,
                                                           :inv_cust_ddm,
                                                           :inv_cust_din,
                                                           :mfcnote_inb_no,
                                                           :bilnote_no,
                                                           :cnote_vuser,
                                                           :cnote_vdate,
                                                           :cnote_refno,
                                                           :cnote_notice,
                                                           :cnote_special_ins,
                                                           :cnote_goods_descr_ins,
                                                           :cashless_hover_doc,
                                                           :cashless_hover_date,
                                                           :cashless_seller_id,
                                                           :cashless_cust_id,
                                                           REPJNE.GET_DATA_SPLIT('~', :mfcnote_inb_date, 2),
                                                           REPJNE.GET_DATA_SPLIT('~', :mfcnote_outb_no, 1),
                                                           REPJNE.GET_DATA_SPLIT('~', :mfcnote_outb_date, 2),
                                                           REPJNE.GET_DATA_SPLIT('~', :mfcnote_transit_no, 1),
                                                           REPJNE.GET_DATA_SPLIT('~', :mfcnote_transit_date, 2),
                                                           :homi_no,
                                                           :homi_date,
                                                           :text1,
                                                           :text2,
                                                           :tdate,
                                                           :freight_charge,
                                                           :surcharge,
                                                           :packing_fee,
                                                           0,  -- SPECIAL_AMOUNT is set to 0
                                                           :discount,
                                                           :discount_card,
                                                           :other_fee,
                                                           :additional_fee,
                                                           :runsheet,
                                                           :pod_date,
                                                           :pod_status,
                                                           :pod_flag,
                                                           :pod_receiver,
                                                           TARIF_NEW(:origin_id, :destination_id, :service_code, :cnote_goods_type, :weight_kg),
                                                           :runsheet_date,
                                                           :courier_id,
                                                           :courier_name
                                                       ) \
                                                """

                            # Eksekusi query insert untuk 2021
                            cursor.execute(insert_query_2021, {
                                "trunc_cnote_date": row[0],
                                "branch": row[1],
                                "awb_date": row[2],
                                "branch_name": row[3],
                                "awb": row[4],
                                "customer_id": row[5],
                                "customer_name": row[6],
                                "service_code": row[7],
                                "origin_id": row[8],
                                "origin_name": row[9],
                                "destination_id": row[10],
                                "destination_name": row[11],
                                "pcs": row[12],
                                "weight_kg": row[13],
                                "cash": row[14],
                                "credit": row[15],
                                "amount": row[16],
                                "goods_value": row[17],
                                "cnote_payment_type": row[18],
                                "insurance_value": row[19],
                                "cnote_currency": row[20],
                                "cnote_curc_rate": row[21],
                                "cnote_printed": row[22],
                                "cnote_manifested": row[23],
                                "cnote_invoiced": row[24],
                                "cnote_cancel": row[25],
                                "cnote_quick": row[26],
                                "bilnote_amount": row[27],
                                "cust_type": row[28],
                                "cust_parent_id": row[29],
                                "reginv": row[30],
                                "reginv_date": row[31],
                                "doc_no": row[32],
                                "rsheet_no": row[33],
                                "pod_date": row[34],
                                "pod_status": row[35],
                                "pod_flag": row[36],
                                "pod_receiver": row[37],
                                "cnote_receiver_name": row[38],
                                "cnote_hold_reason": row[39],
                                "inv_cust_dic": row[40],
                                "inv_cust_ddm": row[41],
                                "inv_cust_din": row[42],
                                "mfcnote_inb_no": row[43],
                                "bilnote_no": row[44],
                                "cnote_vuser": row[45],
                                "cnote_vdate": row[46],
                                "cnote_refno": row[47],
                                "cnote_notice": row[48],
                                "cnote_special_ins": row[49],
                                "cnote_goods_descr_ins": row[50],
                                "cashless_hover_doc": row[51],
                                "cashless_hover_date": row[52],
                                "cashless_seller_id": row[53],
                                "cashless_cust_id": row[54],
                                "mfcnote_inb_date": row[55],
                                "mfcnote_outb_no": row[56],
                                "mfcnote_outb_date": row[57],
                                "mfcnote_transit_no": row[58],
                                "mfcnote_transit_date": row[59],
                                "homi_no": row[60],
                                "homi_date": row[61],
                                "text1": row[62],
                                "text2": row[63],
                                "tdate": row[64],
                                "freight_charge": row[65],
                                "surcharge": row[66],
                                "packing_fee": row[67],
                                "discount": row[68],
                                "discount_card": row[69],
                                "other_fee": row[70],
                                "additional_fee": row[71],
                                "t_2020": row[72],
                                "t_2021": row[73],
                                "goods_type": row[74],
                                "runsheet_date": row[75],
                                "courier_id": row[76],
                                "courier_name": row[77]
                            })

                    else:
                        # Update the record in T_CNOTE_AUD_2021
                        update_query_2021 = """
                                           UPDATE T_CNOTE_AUD_2021
SET 
    TRUNC_CNOTE_DATE = :trunc_cnote_date,
    BRANCH = :branch,
    AWB_DATE = :awb_date,
    BRANCH_NAME = :branch_name,
    CUSTOMER_ID = :customer_id,
    CUSTOMER_NAME = :customer_name,
    SERVICE_CODE = :service_code,
    ORIGIN_ID = :origin_id,
    ORIGIN_NAME = :origin_name,
    DESTINATION_ID = :destination_id,
    DESTINATION_NAME = :destination_name,
    PCS = :pcs,
    WEIGHT_KG = :weight_kg,
    CASH = :cash,
    CREDIT = :credit,
    AMOUNT = :amount,
    GOODS_VALUE = :goods_value,
    CNOTE_PAYMENT_TYPE = :cnote_payment_type,
    INSURANCE_VALUE = :insurance_value,
    CNOTE_CURRENCY = :cnote_currency,
    CNOTE_CURC_RATE = :cnote_curc_rate,
    CNOTE_PRINTED = :cnote_printed,
    CNOTE_MANIFESTED = :cnote_manifested,
    CNOTE_INVOICED = :cnote_invoiced,
    CNOTE_CANCEL = :cnote_cancel,
    CNOTE_QUICK = :cnote_quick,
    BILNOTE_AMOUNT = :bilnote_amount,
    CUST_TYPE = :cust_type,
    CUST_PARENT_ID = :cust_parent_id,
    DOC_NO = :doc_no,
    CNOTE_RECEIVER_NAME = :cnote_receiver_name,
    CNOTE_OTHER_FEE = :cnote_other_fee,
    CNOTE_HOLD_REASON = :cnote_hold_reason,
    INV_CUST_DIC = :inv_cust_dic,
    INV_CUST_DDM = :inv_cust_ddm,
    INV_CUST_DIN = :inv_cust_din,
    CNOTE_VUSER = :cnote_vuser,
    CNOTE_VDATE = :cnote_vdate,
    CNOTE_REFNO = :cnote_refno,
    CNOTE_NOTICE = :cnote_notice,
    CNOTE_SPECIAL_INS = :cnote_special_ins,
    CNOTE_GOODS_DESCR_INS = :cnote_goods_descr_ins,
    FREIGHT_CHARGE = :freight_charge,
    SURCHARGE = :surcharge,
    PACKING_FEE = :packing_fee,
    DISCOUNT = :discount,
    DISCOUNT_CARD = :discount_card,
    OTHER_FEE = :other_fee,
    ADDITIONAL_FEE = :additional_fee,
    MFCNOTE_INB_DATE = REPJNE.GET_DATA_SPLIT('~', :mfcnote_inb_date, 2),
    MFCNOTE_OUTB_NO = REPJNE.GET_DATA_SPLIT('~', :mfcnote_outb_no, 1),
    MFCNOTE_OUTB_DATE = REPJNE.GET_DATA_SPLIT('~', :mfcnote_outb_no, 2),
    MFCNOTE_TRANSIT_NO = REPJNE.GET_DATA_SPLIT('~', :mfcnote_transit_no, 1),
    MFCNOTE_TRANSIT_DATE = REPJNE.GET_DATA_SPLIT('~', :mfcnote_transit_no, 2),
    RUNSHEET = :runsheet_no,
    POD_DATE = :pod_date,
    POD_FLAG = :pod_flag,
    POD_STATUS = :pod_status,
    CNOTE_POD_RECEIVER = :pod_receiver,
    PUBLISH_RATE = TARIF_NEW(:origin_id, :destination_id, :service_code, :cnote_goods_type, :weight_kg),
    RUNSHEET_DATE = TO_DATE(F_GET_POD_STATUS(:awb, 9), 'DD-MON-YYYY HH24:MI:SS'),
    COURIER_ID = F_GET_POD_STATUS(:awb, 4),
    COURIER_NAME = F_GET_POD_STATUS(:awb, 5)
WHERE AWB = :awb  \
                                            """

                        params = {
                            "trunc_cnote_date": row[0],
                            "branch": row[1],
                            "awb_date": row[2],
                            "branch_name": row[3],
                            "customer_id": row[4],
                            "customer_name": row[5],
                            "service_code": row[6],
                            "origin_id": row[7],
                            "origin_name": row[8],
                            "destination_id": row[9],
                            "destination_name": row[10],
                            "pcs": row[11],
                            "weight_kg": row[12],
                            "cash": row[13],
                            "credit": row[14],
                            "amount": row[15],
                            "goods_value": row[16],
                            "cnote_payment_type": row[17],
                            "insurance_value": row[18],
                            "cnote_currency": row[19],
                            "cnote_curc_rate": row[20],
                            "cnote_printed": row[21],
                            "cnote_manifested": row[22],
                            "cnote_invoiced": row[23],
                            "cnote_cancel": row[24],
                            "cnote_quick": row[25],
                            "bilnote_amount": row[26],
                            "cust_type": row[27],
                            "cust_parent_id": row[28],
                            "doc_no": row[29],
                            "cnote_receiver_name": row[30],
                            "cnote_other_fee": row[31],
                            "cnote_hold_reason": row[32],
                            "inv_cust_dic": row[33],
                            "inv_cust_ddm": row[34],
                            "inv_cust_din": row[35],
                            "cnote_vuser": row[36],
                            "cnote_vdate": row[37],
                            "cnote_refno": row[38],
                            "cnote_notice": row[39],
                            "cnote_special_ins": row[40],
                            "cnote_goods_descr_ins": row[41],
                            "freight_charge": row[42],
                            "surcharge": row[43],
                            "packing_fee": row[44],
                            "discount": row[45],
                            "discount_card": row[46],
                            "other_fee": row[47],
                            "additional_fee": row[48],
                            "mfcnote_inb_date": row[49],
                            "mfcnote_outb_no": row[50],
                            "mfcnote_transit_no": row[51],
                            "runsheet_no": row[52],
                            "pod_date": row[53],
                            "pod_flag": row[54],
                            "pod_status": row[55],
                            "pod_receiver": row[56],
                            "awb": row[57]  # Assuming the AWB is the last value in the row
                        }
                        cursor.execute(update_query_2021, params)

                # Commit changes
            connection.commit()

            cursor.close()
            connection.close()

            if result:
                return {"status": "success", "data": result}
            else:
                return {"status": "error", "message": "No data found for the provided p_cnote."}

        else:
            raise Exception("Unable to connect to the database.")

    except Exception as e:
        print(f"Error in JOB_CNOTE_AUDIT: {e}")
        return {"status": "error", "message": str(e)}
